/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integradori;

import Controlador.FormulaControlador;
import Export.ExportarExcel;
import Modelo.conexion;
import java.io.IOException;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steampunkyi
 */
public class Formulacion extends javax.swing.JFrame {

    /**
     * Creates new form Formulacion
     */
    public Formulacion() {
        initComponents();
        mostrar("formula");
        Thread hiloReloj = new Thread(() -> {
        while (true) {
            actualizarHoraYFecha();
            try {
                Thread.sleep(1000); // Actualizar cada segundo
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    });
    hiloReloj.start();
    }
    private void actualizarHoraYFecha() {
        SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        Date horaActual = new Date();
        lblHora.setText(formatoHora.format(horaActual));
        lblFecha.setText(formatoFecha.format(horaActual));
    }
    public void mostrar(String tabla){
        String sql="select*from "+tabla;
        Statement st;
        conexion con=new conexion();
        Connection conexion=con.getConnection();
        System.out.println(sql);
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("idFormula");
        model.addColumn("codigo");
        model.addColumn("producto");
        model.addColumn("insumo");
        model.addColumn("cantidad");
        model.addColumn("insumo");
        model.addColumn("cantidad");
        model.addColumn("insumo");
        model.addColumn("cantidad");
        model.addColumn("insumo");
        model.addColumn("cantidad");
        model.addColumn("insumo");
        model.addColumn("cantidad");
        tbl.setModel(model);
        String [] datos=new String[13];
        try{
            st =conexion.createStatement();
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                model.addRow(datos);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"error"+e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        guardarbtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        consultarbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        insumo1txt = new javax.swing.JTextField();
        insumo2txt = new javax.swing.JTextField();
        insumo3txt = new javax.swing.JTextField();
        insumo4txt = new javax.swing.JTextField();
        insumo5txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cantidad1txt = new javax.swing.JTextField();
        cantidad2txt = new javax.swing.JTextField();
        cantidad3txt = new javax.swing.JTextField();
        cantidad4txt = new javax.swing.JTextField();
        cantidad5txt = new javax.swing.JTextField();
        eliminarbtn = new javax.swing.JButton();
        modificarbtn = new javax.swing.JButton();
        productotxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        report = new javax.swing.JToggleButton();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 22, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(134, 83, 140));
        jLabel5.setText("Fórmula");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(187, 184, 193));
        jLabel7.setText("Producto");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tbl.setBackground(new java.awt.Color(45, 43, 57));
        tbl.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tbl.setForeground(new java.awt.Color(255, 255, 255));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 580, 270));

        guardarbtn.setBackground(new java.awt.Color(47, 44, 57));
        guardarbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        guardarbtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarbtn.setText("GUARDAR");
        guardarbtn.setAutoscrolls(true);
        guardarbtn.setBorder(null);
        guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(guardarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 169, 44));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(187, 184, 193));
        jLabel13.setText("Código");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        codigotxt.setBackground(new java.awt.Color(45, 43, 57));
        codigotxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codigotxt.setForeground(new java.awt.Color(255, 255, 255));
        codigotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigotxt.setBorder(null);
        jPanel2.add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 389, 33));

        consultarbtn.setBackground(new java.awt.Color(47, 44, 57));
        consultarbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultarbtn.setForeground(new java.awt.Color(255, 255, 255));
        consultarbtn.setText("CONSULTAR");
        consultarbtn.setAutoscrolls(true);
        consultarbtn.setBorder(null);
        consultarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(consultarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 150, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(187, 184, 193));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Kg");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 120, -1));

        insumo1txt.setBackground(new java.awt.Color(45, 43, 57));
        insumo1txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insumo1txt.setForeground(new java.awt.Color(255, 255, 255));
        insumo1txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insumo1txt.setBorder(null);
        insumo1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insumo1txtActionPerformed(evt);
            }
        });
        jPanel2.add(insumo1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 27));

        insumo2txt.setBackground(new java.awt.Color(45, 43, 57));
        insumo2txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insumo2txt.setForeground(new java.awt.Color(255, 255, 255));
        insumo2txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insumo2txt.setBorder(null);
        jPanel2.add(insumo2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, 27));

        insumo3txt.setBackground(new java.awt.Color(45, 43, 57));
        insumo3txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insumo3txt.setForeground(new java.awt.Color(255, 255, 255));
        insumo3txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insumo3txt.setBorder(null);
        jPanel2.add(insumo3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, 27));

        insumo4txt.setBackground(new java.awt.Color(45, 43, 57));
        insumo4txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insumo4txt.setForeground(new java.awt.Color(255, 255, 255));
        insumo4txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insumo4txt.setBorder(null);
        jPanel2.add(insumo4txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 27));

        insumo5txt.setBackground(new java.awt.Color(45, 43, 57));
        insumo5txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insumo5txt.setForeground(new java.awt.Color(255, 255, 255));
        insumo5txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insumo5txt.setBorder(null);
        jPanel2.add(insumo5txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 29));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(187, 184, 193));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Insumos");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 170, -1));

        cantidad1txt.setBackground(new java.awt.Color(45, 43, 57));
        cantidad1txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad1txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad1txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad1txt.setBorder(null);
        cantidad1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad1txtActionPerformed(evt);
            }
        });
        jPanel2.add(cantidad1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, 27));

        cantidad2txt.setBackground(new java.awt.Color(45, 43, 57));
        cantidad2txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad2txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad2txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad2txt.setBorder(null);
        cantidad2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2txtActionPerformed(evt);
            }
        });
        jPanel2.add(cantidad2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 70, 30));

        cantidad3txt.setBackground(new java.awt.Color(45, 43, 57));
        cantidad3txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad3txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad3txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad3txt.setBorder(null);
        cantidad3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad3txtActionPerformed(evt);
            }
        });
        jPanel2.add(cantidad3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 30));

        cantidad4txt.setBackground(new java.awt.Color(45, 43, 57));
        cantidad4txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad4txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad4txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad4txt.setBorder(null);
        jPanel2.add(cantidad4txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 70, 30));

        cantidad5txt.setBackground(new java.awt.Color(45, 43, 57));
        cantidad5txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad5txt.setForeground(new java.awt.Color(255, 255, 255));
        cantidad5txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad5txt.setBorder(null);
        jPanel2.add(cantidad5txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 70, 30));

        eliminarbtn.setBackground(new java.awt.Color(47, 44, 57));
        eliminarbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarbtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarbtn.setText("ELIMINAR");
        eliminarbtn.setAutoscrolls(true);
        eliminarbtn.setBorder(null);
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(eliminarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 130, 50));

        modificarbtn.setBackground(new java.awt.Color(47, 44, 57));
        modificarbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificarbtn.setForeground(new java.awt.Color(255, 255, 255));
        modificarbtn.setText("MODIFICAR");
        modificarbtn.setAutoscrolls(true);
        modificarbtn.setBorder(null);
        modificarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(modificarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 140, 50));

        productotxt.setBackground(new java.awt.Color(45, 43, 57));
        productotxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productotxt.setForeground(new java.awt.Color(255, 255, 255));
        productotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productotxt.setBorder(null);
        jPanel2.add(productotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 389, 38));

        idtxt.setEditable(false);
        idtxt.setBackground(new java.awt.Color(45, 43, 57));
        idtxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idtxt.setForeground(new java.awt.Color(255, 255, 255));
        idtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idtxt.setBorder(null);
        jPanel2.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 50, 30));

        report.setBackground(new java.awt.Color(47, 44, 57));
        report.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("REPORTE");
        report.setAutoscrolls(true);
        report.setBorder(null);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel2.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 169, 44));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(187, 184, 193));
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 140, 30));

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 900, 650));

        jPanel1.setBackground(new java.awt.Color(37, 32, 47));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(37, 32, 47));
        jPanel10.setForeground(new java.awt.Color(187, 184, 193));
        jPanel10.setPreferredSize(new java.awt.Dimension(226, 45));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(187, 184, 193));
        jLabel16.setText("Mantenimiento");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel16)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jPanel7.setBackground(new java.awt.Color(47, 44, 57));
        jPanel7.setPreferredSize(new java.awt.Dimension(226, 45));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(193, 117, 121));
        jLabel8.setText("Fórmula");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel8)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jPanel8.setBackground(new java.awt.Color(37, 32, 47));
        jPanel8.setPreferredSize(new java.awt.Dimension(226, 45));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(187, 184, 193));
        jLabel17.setText("Registro");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel17)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jPanel4.setBackground(new java.awt.Color(37, 32, 47));
        jPanel4.setPreferredSize(new java.awt.Dimension(226, 45));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 184, 193));
        jLabel3.setText("Inicio");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtnActionPerformed
        mostrar("formula");
    }//GEN-LAST:event_guardarbtnActionPerformed

    private void consultarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarbtnActionPerformed

    private void insumo1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insumo1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insumo1txtActionPerformed

    private void cantidad1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad1txtActionPerformed

    private void cantidad3txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad3txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad3txtActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
        mostrar("formula");
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void modificarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarbtnActionPerformed
        mostrar("formula");
    }//GEN-LAST:event_modificarbtnActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        ExportarExcel obj;

        try {
            obj = new ExportarExcel();
            obj.exportarExcel(tbl);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
 
    }//GEN-LAST:event_reportActionPerformed

    private void cantidad2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad2txtActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        PantallaInicio yy=new PantallaInicio();
        yy.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        OrdenProduccion yy=new OrdenProduccion();
        yy.setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        Mantenimiento yy=new Mantenimiento();
        yy.setVisible(true);
    }//GEN-LAST:event_jPanel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Formulacion v=new Formulacion();
       FormulaControlador c=new FormulaControlador(v);
       v.setVisible(true);
       v.setLocationRelativeTo(v);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cantidad1txt;
    public javax.swing.JTextField cantidad2txt;
    public javax.swing.JTextField cantidad3txt;
    public javax.swing.JTextField cantidad4txt;
    public javax.swing.JTextField cantidad5txt;
    public javax.swing.JTextField codigotxt;
    public javax.swing.JButton consultarbtn;
    public javax.swing.JButton eliminarbtn;
    public javax.swing.JButton guardarbtn;
    public javax.swing.JTextField idtxt;
    public javax.swing.JTextField insumo1txt;
    public javax.swing.JTextField insumo2txt;
    public javax.swing.JTextField insumo3txt;
    public javax.swing.JTextField insumo4txt;
    public javax.swing.JTextField insumo5txt;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblHora;
    public javax.swing.JButton modificarbtn;
    public javax.swing.JTextField productotxt;
    public javax.swing.JToggleButton report;
    public javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
