package com.mycompany.integradori;

import Modelo.condicionMant;
import Modelo.condicionMantDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class Mantenimiento extends javax.swing.JFrame {
    condicionMantDAO dao = new condicionMantDAO();
    condicionMant cd = new condicionMant();
    
    DefaultTableModel modelo = new DefaultTableModel();
    public Mantenimiento() {
        initComponents();
        listar();
    }

    
void listar(){
    @SuppressWarnings("unchecked")
    List<condicionMant> lista = dao.listar();
    //List<? extends condicionMant> lista = new ArrayList<>(dao.listar());
    modelo = (DefaultTableModel)jTable2.getModel();
    Object[]ob = new Object[7];
    for (int i = 0; i < lista.size(); i++) {
        ob[0]=lista.get(i).getIdCondicionMant();
        ob[1]=lista.get(i).getTolvaRPM();
        ob[2]=lista.get(i).getTornilloRPM();
        ob[3]=lista.get(i).getPresion();
        ob[4]=lista.get(i).getAmperaje();
        ob[5]=lista.get(i).getVacio();
        ob[6]=lista.get(i).getRendimiento();
        modelo.addRow(ob);
    }
    jTable2.setModel(modelo);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtPresion = new javax.swing.JTextField();
        txtTolvaRPM = new javax.swing.JTextField();
        txtTornilloRPM = new javax.swing.JTextField();
        txtRendimiento = new javax.swing.JTextField();
        txtAmperaje = new javax.swing.JTextField();
        txtVacio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btncond = new javax.swing.JButton();
        btncond1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        btncond2 = new javax.swing.JButton();
        btncond3 = new javax.swing.JButton();
        btncond4 = new javax.swing.JButton();
        btncond5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 32, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(187, 184, 193));
        jLabel4.setText("Registro");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(187, 184, 193));
        jLabel8.setText("Fórmula");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jPanel9.setBackground(new java.awt.Color(47, 44, 57));
        jPanel9.setPreferredSize(new java.awt.Dimension(226, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(193, 117, 121));
        jLabel5.setText("Mantenimiento");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 37));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagen/Recurso 1 (Custom) (Custom).png.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(187, 184, 193));
        jLabel10.setText("Atrás");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(187, 184, 193));
        jLabel3.setText("Inicio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 650));

        jPanel2.setBackground(new java.awt.Color(26, 22, 31));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(187, 184, 193));
        jLabel11.setText("Temperatura en Zonas");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 26));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(187, 184, 193));
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 110, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(134, 83, 140));
        jLabel14.setText("Mantenimiento");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(187, 184, 193));
        jLabel15.setText("N° OF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(187, 184, 193));
        jLabel17.setText("Producto");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(187, 184, 193));
        jLabel18.setText("Rendimiento");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(187, 184, 193));
        jLabel19.setText("Responsable");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(187, 184, 193));
        jLabel22.setText("Tolva RPM");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(187, 184, 193));
        jLabel23.setText("Tornillo RPM");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(187, 184, 193));
        jLabel21.setText("Presión");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(187, 184, 193));
        jLabel24.setText("Amperaje");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 230, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(187, 184, 193));
        jLabel25.setText("Vacío");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        txtPresion.setBackground(new java.awt.Color(47, 44, 57));
        txtPresion.setForeground(new java.awt.Color(204, 204, 204));
        txtPresion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPresion.setBorder(null);
        jPanel2.add(txtPresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 90, 30));

        txtTolvaRPM.setBackground(new java.awt.Color(47, 44, 57));
        txtTolvaRPM.setForeground(new java.awt.Color(204, 204, 204));
        txtTolvaRPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTolvaRPM.setBorder(null);
        txtTolvaRPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTolvaRPMActionPerformed(evt);
            }
        });
        jPanel2.add(txtTolvaRPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 30));

        txtTornilloRPM.setBackground(new java.awt.Color(47, 44, 57));
        txtTornilloRPM.setForeground(new java.awt.Color(204, 204, 204));
        txtTornilloRPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTornilloRPM.setBorder(null);
        txtTornilloRPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTornilloRPMActionPerformed(evt);
            }
        });
        jPanel2.add(txtTornilloRPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, 30));

        txtRendimiento.setBackground(new java.awt.Color(47, 44, 57));
        txtRendimiento.setForeground(new java.awt.Color(204, 204, 204));
        txtRendimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRendimiento.setBorder(null);
        jPanel2.add(txtRendimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 90, 30));

        txtAmperaje.setBackground(new java.awt.Color(47, 44, 57));
        txtAmperaje.setForeground(new java.awt.Color(204, 204, 204));
        txtAmperaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAmperaje.setBorder(null);
        jPanel2.add(txtAmperaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 90, 30));

        txtVacio.setBackground(new java.awt.Color(47, 44, 57));
        txtVacio.setForeground(new java.awt.Color(204, 204, 204));
        txtVacio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVacio.setBorder(null);
        txtVacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVacioActionPerformed(evt);
            }
        });
        jPanel2.add(txtVacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Z1", "Z2", "Z3", "Z4", "Z5", "Z6", "Z7", "Z8", "Z9", "Z10", "Z11", "Z12"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 710, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(187, 184, 193));
        jLabel26.setText("Condiciones de Operación");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(187, 184, 193));
        jLabel27.setText("Z6");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 410, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(187, 184, 193));
        jLabel29.setText("Z1");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 410, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(187, 184, 193));
        jLabel30.setText("Z2");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 410, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(187, 184, 193));
        jLabel31.setText("Z3");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 410, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(187, 184, 193));
        jLabel32.setText("Z4");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 410, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(187, 184, 193));
        jLabel33.setText("Z5");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 410, -1, -1));

        jTextField8.setBackground(new java.awt.Color(47, 44, 57));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(null);
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 50, 30));

        jTextField9.setBackground(new java.awt.Color(47, 44, 57));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 50, 30));

        jTextField10.setBackground(new java.awt.Color(47, 44, 57));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 50, 30));

        jTextField11.setBackground(new java.awt.Color(47, 44, 57));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(null);
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 50, 30));

        jTextField12.setBackground(new java.awt.Color(47, 44, 57));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(null);
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 50, 30));

        jTextField13.setBackground(new java.awt.Color(47, 44, 57));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(null);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 50, 30));

        jTable2.setBackground(new java.awt.Color(153, 153, 153));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tolva RPM", "Tornillo RPM", "Presion", "Amperaje", "Vacio", "Rendimiento"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 710, 50));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(187, 184, 193));
        jLabel34.setText("Z12");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(187, 184, 193));
        jLabel35.setText("Z7");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 410, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(187, 184, 193));
        jLabel36.setText("Z8");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(187, 184, 193));
        jLabel37.setText("Z9");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 410, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(187, 184, 193));
        jLabel38.setText("Z10");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(187, 184, 193));
        jLabel39.setText("Z11");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        jTextField14.setBackground(new java.awt.Color(47, 44, 57));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(null);
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 50, 30));

        jTextField15.setBackground(new java.awt.Color(47, 44, 57));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setBorder(null);
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 50, 30));

        jTextField16.setBackground(new java.awt.Color(47, 44, 57));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 50, 30));

        jTextField17.setBackground(new java.awt.Color(47, 44, 57));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setBorder(null);
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 50, 30));

        jTextField18.setBackground(new java.awt.Color(47, 44, 57));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setBorder(null);
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 50, 30));

        jTextField19.setBackground(new java.awt.Color(47, 44, 57));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setBorder(null);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 50, 30));

        jComboBox1.setBackground(new java.awt.Color(47, 44, 57));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Juan Perez", "Luis Ordoñez", "Mario Garrala", "Pedro Dominguez", "Miguel Juarez", "Daniel Valencia" }));
        jComboBox1.setToolTipText("");
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 142, 280, 30));

        btncond.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btncond.setText("Reporte");
        btncond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncondActionPerformed(evt);
            }
        });
        jPanel2.add(btncond, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 120, 40));

        btncond1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncond1.setText("Editar");
        btncond1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncond1ActionPerformed(evt);
            }
        });
        jPanel2.add(btncond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 80, 40));

        jTextField2.setBackground(new java.awt.Color(47, 44, 57));
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 280, 30));

        jTextField20.setBackground(new java.awt.Color(47, 44, 57));
        jTextField20.setBorder(null);
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 280, 30));

        btncond2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btncond2.setText("Aceptar");
        btncond2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncond2ActionPerformed(evt);
            }
        });
        jPanel2.add(btncond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 120, 40));

        btncond3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncond3.setText("Agregar");
        btncond3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncond3ActionPerformed(evt);
            }
        });
        jPanel2.add(btncond3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 80, 40));

        btncond4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncond4.setText("Agregar");
        btncond4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncond4ActionPerformed(evt);
            }
        });
        jPanel2.add(btncond4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 80, 40));

        btncond5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncond5.setText("Editar");
        btncond5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncond5ActionPerformed(evt);
            }
        });
        jPanel2.add(btncond5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 490, 80, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 900, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        OrdenProduccion yy=new OrdenProduccion();
        yy.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Formulacion yy=new Formulacion();
        yy.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Mantenimiento yy=new Mantenimiento();
        yy.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtTornilloRPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTornilloRPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTornilloRPMActionPerformed

    private void txtVacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVacioActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void btncondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncondActionPerformed

    private void btncond1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncond1ActionPerformed
        actualizar();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btncond1ActionPerformed

    private void btncond2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncond2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncond2ActionPerformed

    private void btncond3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncond3ActionPerformed
        agregar();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btncond3ActionPerformed

    private void btncond4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncond4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncond4ActionPerformed

    private void btncond5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncond5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncond5ActionPerformed

    private void txtTolvaRPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTolvaRPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTolvaRPMActionPerformed
    
    void agregar() {
        String TolvaRPM = txtTolvaRPM.getText();
        String TornilloRPM = txtTornilloRPM.getText();
        String Presion = txtPresion.getText();
        String Amperaje = txtAmperaje.getText();
        String Vacio = txtVacio.getText();
        String Rendimiento = txtRendimiento.getText();
        Object[] ob = new Object[6];
        ob[0] = TolvaRPM;
        ob[1] = TornilloRPM; 
        ob[2] = Presion;
        ob[3] = Amperaje;
        ob[4] = Vacio;
        ob[5] = Rendimiento;
        dao.add(ob);
    }
    
    void actualizar() {
        
    }
    
    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncond;
    public javax.swing.JButton btncond1;
    public javax.swing.JButton btncond2;
    public javax.swing.JButton btncond3;
    public javax.swing.JButton btncond4;
    public javax.swing.JButton btncond5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField17;
    public javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblHora;
    public javax.swing.JTextField txtAmperaje;
    public javax.swing.JTextField txtPresion;
    public javax.swing.JTextField txtRendimiento;
    public javax.swing.JTextField txtTolvaRPM;
    public javax.swing.JTextField txtTornilloRPM;
    public javax.swing.JTextField txtVacio;
    // End of variables declaration//GEN-END:variables
}
